### PR TITLE
Construct proper debug path

### LINKED ISSUE #360: debug path is broken when swaggerBase is configured
There's a bug in generating the URL in the `OpenAPIInflector.java` for the debug endpoint which only happens when the `inflector.yaml` has a non-null `swaggerBase` configured. Ironically that's what is in the integration tests 🤷🏻‍♂️

### PR DESCRIPTION
**Pull request by fehguy**
Fixes #360, builds on top of #359

### CODE REVIEW

File: src/main/java/io/swagger/oas/inflector/OpenAPIInflector.java [hunk 1]
```diff
@@ -358,7 +358,17 @@ protected void init(Configuration configuration) {
                 }
             }
             final Resource.Builder builder = Resource.builder();
-            builder.path(basePath(originalBasePath, config.getSwaggerBase() + "debug.json"))
```
Comment (fehguy) [inline src/main/java/io/swagger/oas/inflector/OpenAPIInflector.java]: when `config.getSwaggerBase()` returns a value, it does not have a trailing `/` and we end up with a mashed `swaggerdebug.json` as the path in the integration tests.

File: src/test/java/io/swagger/oas/test/integration/SwaggerListingIT.java [hunk 2]
```diff
@@ -57,6 +57,20 @@ public void verifySwaggerYaml() throws Exception {
...
+        client.invokeAPI("/swagger/debug.json",
+                "GET",
+                new HashMap<String, String>(),
+                null,
+                new HashMap<String, String>(),
+                null,
+                "application/json",
+                null,
+                new String[0]);
+    }
```
Comment (fehguy) [inline src/test/java/io/swagger/oas/test/integration/SwaggerListingIT.java]: an exception will be raised if the path doesn't exist
